### ISSUE TITLE
PIP installation of requirements fail

### ISSUE THREAD

**Issue by cbarreholm** [dainnilsson/flask-u2f-tutorial#1]
...
  Running setup.py (path:/tmp/pip_build_christer/u2fval-client/setup.py) egg_info for package u2fval-client
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_christer/u2fval-client/setup.py", line 29, in <module>
        from release import release
    ImportError: No module named release
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_christer/u2fval-client/setup.py", line 29, in <module>

    from release import release

ImportError: No module named release

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_christer...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_christer/u2fval-client
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_christer/u2fval-client

**Comment by dainnilsson** [comment]
Ugh... Sorry, I'll fix that.

**Comment by dainnilsson** [comment]
Ok, it should work now. Version should be 1.0.1

**Comment by cbarreholm** [comment]
It works, but I had to modify the version to 1.0.1 manually. Pushed on master?

**Comment by dainnilsson** [comment]
Ah, the requirements.txt file has the version specified to be 1.0.0 (changed now). I don't have time to now, but I'm going to rebase that change in and redo the tags at some point, which will require a force-push, so, opening this issue again...

**Comment by dainnilsson** [comment]
Ok, I've force pushed everything. Delete the repo and clone it again, and all should be well.
