### ISSUE TITLE
Doesnt work MacOS

### ISSUE THREAD

**Issue by JERINJACOBCHERIAN** [dainnilsson/flask-u2f-tutorial#6]
JERINs-MacBook-Air:flask-u2f-tutorial-tutorial-7 jerinjacobcherian$ python minitwit_tests.py
EE.E
======================================================================
ERROR: test_login_logout (__main__.MiniTwitTestCase)
Make sure logging in and logging out works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "minitwit_tests.py", line 89, in test_login_logout
    rv = self.register_and_login('user1', 'default')
  File "minitwit_tests.py", line 55, in register_and_login
    return self.login(username, password)
  File "minitwit_tests.py", line 50, in login
    }, follow_redirects=True)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 801, in post
    return self.open(*args, **kw)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 764, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 677, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 884, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jerinjacobcherian/Downloads/flask-u2f-tutorial-tutorial-7/minitwit.py", line 228, in login
    auth_req = u2fval.auth_begin(str(user['user_id']))
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/u2fval_client/client.py", line 125, in auth_begin
    return self._req('GET', url, params=params)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/u2fval_client/client.py", line 69, in _req
    'The server responded with invalid data')
InvalidResponseException: The server responded with invalid data

======================================================================
ERROR: test_message_recording (__main__.MiniTwitTestCase)
Check if adding messages works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "minitwit_tests.py", line 100, in test_message_recording
    self.register_and_login('foo', 'default')
  File "minitwit_tests.py", line 55, in register_and_login
    return self.login(username, password)
  File "minitwit_tests.py", line 50, in login
    }, follow_redirects=True)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 801, in post
    return self.open(*args, **kw)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 764, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 677, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 884, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jerinjacobcherian/Downloads/flask-u2f-tutorial-tutorial-7/minitwit.py", line 228, in login
    auth_req = u2fval.auth_begin(str(user['user_id']))
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/u2fval_client/client.py", line 125, in auth_begin
    return self._req('GET', url, params=params)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/u2fval_client/client.py", line 69, in _req
    'The server responded with invalid data')
InvalidResponseException: The server responded with invalid data

======================================================================
ERROR: test_timelines (__main__.MiniTwitTestCase)
Make sure that timelines work
----------------------------------------------------------------------
Traceback (most recent call last):
  File "minitwit_tests.py", line 109, in test_timelines
    self.register_and_login('foo', 'default')
  File "minitwit_tests.py", line 55, in register_and_login
    return self.login(username, password)
  File "minitwit_tests.py", line 50, in login
    }, follow_redirects=True)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 801, in post
    return self.open(*args, **kw)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 764, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 677, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/werkzeug/test.py", line 884, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jerinjacobcherian/Downloads/flask-u2f-tutorial-tutorial-7/minitwit.py", line 228, in login
    auth_req = u2fval.auth_begin(str(user['user_id']))
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/u2fval_client/client.py", line 125, in auth_begin
    return self._req('GET', url, params=params)
  File "/Users/jerinjacobcherian/anaconda/lib/python2.7/site-packages/u2fval_client/client.py", line 69, in _req
    'The server responded with invalid data')
InvalidResponseException: The server responded with invalid data

----------------------------------------------------------------------
Ran 4 tests in 0.573s

FAILED (errors=3)

**Comment by dainnilsson** [comment]
The tests are a remnant from the Flask minitwit example, and are not expected to work as this tutorial changes the way registration and authentication works. The note about tests at the bottom of the README is unfortunate, but also something that was simply copied from the original example project. I'll remove it and the tests now to avoid this misunderstanding in the future.
